### ISSUE TITLE
Межбуквенное расстояние шрифтов

### ISSUE THREAD

**Issue by Mike-magic** [siyanie/siyanie-ui#1]
В шрифтах меню, телефона, основном текстовом блоке и в фразе (плюс подписи к фразе) не соблюдены межбуквенные расстояния.
[Текстовые блоки](http://prntscr.com/d7z3x4)
[Меню](http://prntscr.com/d7z48m)
[Фраза](http://prntscr.com/d7z4gi)
Подпись к фразе тоже проверьте

**Comment by yepninja** [comment]
Поправить межбуквенные расстояние в:
- [x] [Текстовых блоках](http://prntscr.com/d7z3x4)
- [x] [Меню](http://prntscr.com/d7z48m)
- [x] [Фразах](http://prntscr.com/d7z4gi)

**Comment by Mike-magic** [comment]
- [x] Меню http://prntscr.com/d81c5y
- [x] Телефон  http://prntscr.com/d81f2h
- [x] Дата http://prntscr.com/d81exe
- [x] Заголовок http://prntscr.com/d81f6f
- [x] Текст http://prntscr.com/d81cje
- [x] Фраза http://prntscr.com/d81cdh
- [x] Автор фразы  http://prntscr.com/d81fs3
- [x] Ссылка подробнее http://prntscr.com/d81fb4
- [x] Текст в футере http://prntscr.com/d81gal
