### ISSUE TITLE
Верстка телефона

### ISSUE THREAD

**Issue by Mike-magic** [siyanie/siyanie-ui#2]
[Слева макет, справа верстка](http://prntscr.com/d7z5rg)
Видно что межбуквенное расстояние неверное, 495 меньшим шрифтм - а так не надо, иконка не выровнена относительно телефона.

**Comment by yepninja** [comment]
- [x] выровнять межбуквенное растояние
- [x] исправить размер шрифта "495"
- [x] выровнять иконку
- [x] растояние от префикса до номера
